;* Yggdrasil (TM) Core Operating System (65C02): Character Library
;* Copyright (C) DeRemee Systems, IXE Electronics LLC
;* Portions copyright IXE Electronics LLC, Republic Robotics,
;* FemtoLaunch, FemtoSat, FemtoTrack, Weland
;* This work is made available under the Creative Commons
;* Attribution-NonCommercial-ShareAlike 4.0 International License.
;* To view a copy of this license, visit
;* http://creativecommons.org/licenses/by-nc-sa/4.0/.


;CONVERTS A SINGLE DIGIT HEX VALUE TO A CHARACTER
;ON ENTRY:
;	A = SINGLE DIGIT HEX VALUE
;ON RETURN:
;	A = VALUE ON ENTRY
;	C = 0 IF VALUE IS HEXADECIMAL
;	C = 1 IF VALUE IS NOT HEXADECIMAL
CHARFROMHEX:
	;VALUE > 0x0F?
	CMP		#0x10
	BPL		CHARFROMHEXB
	;CONVERT TO CHARACTER
	CLC
	ADC		#0x30
	;CHARACTER > "9"?
	CMP		#0x3A
	BMI		CHARFROMHEXA
	;ADD 0x07 TO CHARACTER
	CLC
	ADC		#0x07
CHARFROMHEXA:
	RTS
CHARFROMHEXB:
	LDA		#0x00
	RTS


;CONVERTS A SINGLE DIGIT INTEGER TO A CHARACTER
;ON ENTRY:
;	A = SINGLE DIGIT INTEGER
;ON RETURN:
;	A = VALUE ON ENTRY
;	C = 0 IF VALUE IS AN INTEGER
;	C = 1 IF VALUE IS NOT AN INTEGER
CHARFROMINT:
	;VALUE > 0x09?
	CMP		#0x0A
	BPL		CHARFROMINTA
	;CONVERT TO CHARACTER
	CLC
	ADC		#0x30
	RTS
CHARFROMINTA:
	LDA		#0x00
	RTS


;CONVERTS THE HEX CHARACTER IN A TO AN INTEGER
;ON ENTRY:
;	A = VALUE
;ON RETURN:
;	C = 0 IF CHARACTER IS HEX
;			A = INTEGER VALUE
;	C = 1 IF CHARACTER IS NOT HEX
;			A = 0x00
CHARHEXTOINT:
	;CHECK FOR LESS THAN "0"
	SEC
	SBC		#0x30
	BMI		CHARHEXTOINTD
	;CHECK FOR GREATER THAN "9"
	CMP		#0x0A
	BPL		CHARHEXTOINTB
CHARHEXTOINTA:
	CLC
	RTS
CHARHEXTOINTB:
	;SUBTRACT 0x07
	SBC		#0x07
CHARHEXTOINTC:
	;CHECK FOR LESS THAN "A"
	CMP		#0x0A
	BMI		CHARHEXTOINTD
	;CHECK FOR GREATER THAN "F"
	CMP		#0x10
	BMI		CHARHEXTOINTA
	;CONVERT TO UPPERCASE
	SBC		#0x20
	BMI		CHARHEXTOINTD
	;CHECK FOR LESS THAN "A"
	CMP		#0x0A
	BMI		CHARHEXTOINTD
	;CHECK FOR GREATER THAN "F"
	CMP		#0x10
	BMI     CHARHEXTOINTA
CHARHEXTOINTD:
	LDA		#0x00
	SEC
	RTS


;RETURNS TRUE IF VALUE IS AN ARITHMETIC OPERATOR
;ON ENTRY:
;	A = VALUE
;ON RETURN:
;	A = VALUE ON ENTRY
;	C = 0 IF VALUE IS NOT AN ARITHMETIC OPERATOR
;	C = 1 IF VALUE IS AN ARITHMETIC OPERATOR
CHARISARITH:	
	;CHECK FOR FACTORAL "!"
	CMP		#0x21
	BEQ		CHARISARITHA	
	;CHECK FOR MODULO "%"
	CMP		#0x25
	BEQ		CHARISARITHA	
	;CHECK FOR MULTIPLICATION "*"
	CMP		#0x2A
	BEQ		CHARISARITHA	
	;CHECK FOR ADDITION "+"
	CMP		#0x2B
	BEQ		CHARISARITHA
	;CHECK FOR SUBTRACTION "-"
	CMP		#0x2D
	BEQ		CHARISARITHA
	;CHECK FOR DIVISION "/"
	CMP		#0x2F
	BEQ		CHARISARITHA
	;CHECK FOR EQUALS "="
	CMP		#0x3D
	BEQ		CHARISARITHA
	;CHECK FOR EXPONENT "^"
	CMP		#0x5E
	BNE		CHARISARITHB
CHARISARITHA:
	SEC
	RTS
CHARISARITHB:
	CLC
	RTS


;RETURNS TRUE IF VALUE IS A CLOSING BRACKET
;ON ENTRY:
;	A = VALUE
;ON RETURN:
;	A = VALUE ON ENTRY
;	C = 0 IF VALUE IS NOT A CLOSING BRACKET
;	C = 1 IF VALUE IS AN A CLOSING BRACKET
CHARISBRACC:
	;CHECK FOR ")"
	CMP		#0x29
	BEQ		CHARISBRACCA
	;CHECK FOR "]"
	CMP		#0x5D
	BEQ		CHARISBRACCA
	;CHECK FOR "}"
	CMP		#0x7D
	BNE		CHARISBRACCB
CHARISBRACCA:
	SEC
	RTS
CHARISBRACCB:
	CLC
	RTS


;RETURNS TRUE IF VALUE IS AN OPENING BRACKET
;ON ENTRY:
;	A = VALUE
;ON RETURN:
;	A = VALUE ON ENTRY
;	C = 0 IF VALUE IS NOT AN OPENING BRACKET
;	C = 1 IF VALUE IS AN AN OPENING BRACKET
CHARISBRACO:
	;CHECK FOR "("
	CMP		#0x28
	BEQ		CHARISBRACOA
	;CHECK FOR "["
	CMP		#0x5B
	BEQ		CHARISBRACOA
	;CHECK FOR "{"
	CMP		#0x7B
	BNE		CHARISBRACOB
CHARISBRACOA:
	SEC
	RTS
CHARISBRACOB:
	CLC
	RTS


;RETURNS TRUE IF VALUE IS A NON-PRINTING CHARACTER
;ON ENTRY:
;	A = VALUE
;ON RETURN:
;	A = VALUE ON ENTRY
;	C = 0 IF VALUE IS NOT A NON-PRINTING CHARACTER
;	C = 1 IF VALUE IS A NON-PRINTING CHARACTER
CHARISNPC:
	;CHECK FOR LESS THAN 0x20
	CMP		#0x20
	BMI		CHARISNPCA	
	;CHECK FOR 0x7F
	CMP		#0x7F
	BEQ		CHARISNPCA	
	CLC
	RTS
CHARISNPCA:
	SEC
	RTS


;RETURNS TRUE IF VALUE IS A HEX CHARACTER
;ON ENTRY:
;	A = VALUE
;ON RETURN:
;	A = VALUE ON ENTRY
;	C = 0 IF VALUE IS NOT A HEX CHARACTER
;	C = 1 IF VALUE IS A HEX CHARACTER
CHARISHEX:
	;CHECK FOR LESS THAN "0"
	CMP		#0x30
	BMI		CHARISHEXA	
	;CHECK FOR GREATER THAN "9"
	CMP		#0x3A
	BMI		CHARISHEXB	
	;CHECK FOR LESS THAN "A"
	CMP		#0x41
	BMI		CHARISHEXA	
	;CHECK FOR GREATER THAN "F"
	CMP		#0x47
	BMI		CHARISHEXB	
	;CHECK FOR LESS THAN "a"
	CMP		#0x61
	BMI		CHARISHEXA	
	;CHECK FOR GREATER THAN "f"
	CMP		#0x67
	BMI		CHARISHEXB	
CHARISHEXA:
	CLC
	RTS
CHARISHEXB:
	SEC
	RTS


;RETURNS TRUE IF VALUE IS A LETTER
;ON ENTRY:
;	A = VALUE
;ON RETURN:
;	A = VALUE ON ENTRY
;	C = 0 IF VALUE IS NOT A LETTER
;	C = 1 IF VALUE IS A LETTER
CHARISLETTER:
	;CHECK FOR LESS THAN "A"
	CMP		#0x41
	BMI		CHARISLETTERA
	;CHECK FOR GREATER THAN "Z"
	CMP		#0x5B
	BMI		CHARISLETTERB
	;CHECK FOR LESS THAN "a"
	CMP		#0x61
	BMI		CHARISLETTERA
	;CHECK FOR GREATER THAN "z"
	CMP		#0x7B
	BMI		CHARISLETTERB
CHARISLETTERA:
	CLC
	RTS
CHARISLETTERB:
	SEC
	RTS


;RETURNS TRUE IF VALUE IS A LOGICAL OPERATOR
;ON ENTRY:
;	A = VALUE
;ON RETURN:
;	A = VALUE ON ENTRY
;	C = 0 IF VALUE IS NOT A LOGICAL OPERATOR
;	C = 1 IF VALUE IS AN A LOGICAL OPERATOR
CHARISLOGIC:
	;CHECK FOR NOT "!"
	CMP		#0x21
	BEQ		CHARISLOGICA
	;CHECK FOR AND "&"
	CMP		#0x26
	BEQ		CHARISLOGICA
	;CHECK FOR XOR "^"
	CMP		#0x5E
	BEQ		CHARISLOGICA
	;CHECK FOR OR "|"
	CMP		#0x7C
	BNE		CHARISLOGICB
CHARISLOGICA:
	SEC
	RTS
CHARISLOGICB:
	CLC
	RTS



;RETURNS TRUE IF VALUE IS A LOWERCASE LETTER
;ON ENTRY:
;	A = VALUE
;ON RETURN:
;	A = VALUE ON ENTRY
;	CF = 0 IF VALUE IS NOT A LOWERCASE LETTER
;	CF = 1 IF VALUE IS A LOWERCASE LETTER
CHARISLOWER:
	;CHECK FOR LESS THAN "a"
	CMP		#0x61
	BMI		CHARISLOWERA
	;CHECK FOR GREATER THAN "z"
	CMP		#0x7B
	BMI		CHARISLOWERB
CHARISLOWERA:
	CLC
	RTS
CHARISLOWERB:
	SEC
	RTS


;RETURNS TRUE IF VALUE IS A NUMBER
;ON ENTRY:
;	A = VALUE
;ON RETURN:
;	A = VALUE ON ENTRY
;	C = 0 IF VALUE IS NOT A NUMBER
;	C = 1 IF VALUE IS A NUMBER
CHARISNUMBER:
	;CHECK FOR LESS THAN "0"
	CMP		#0x30
	BMI		CHARISNUMBERA
	;CHECK FOR GREATER THAN "9"
	CMP		#0x3A
	BMI		CHARISNUMBERB
CHARISNUMBERA:
	CLC
	RTS
CHARISNUMBERB:
	SEC
	RTS


;RETURNS TRUE IF VALUE IS PUNCTUATION
;ON ENTRY:
;	A = VALUE
;ON RETURN:
;	A = VALUE ON ENTRY
;	C = 0 IF VALUE IS NOT PUNCTUATION
;	C = 1 IF VALUE IS PUNCTUATION
CHARISPUNCT:
	;CHECK FOR "!"
	CMP		#0x21
	BEQ		CHARISPUNCTA
	;CHECK FOR "."
	CMP		#0x2E
	BEQ		CHARISPUNCTA
	;CHECK FOR "?"
	CMP		#0x3F
	BNE		CHARISPUNCTB
CHARISPUNCTA:
	SEC
	RTS
CHARISPUNCTB:
	CLC
	RTS


;RETURNS TRUE IF VALUE IS A RELATIONAL OPERATOR
;ON ENTRY:
;	A = VALUE
;ON RETURN:
;	A = VALUE ON ENTRY
;	C = 0 IF VALUE IS NOT A RELATIONAL OPERATOR
;	C = 1 IF VALUE IS A RELATIONAL OPERATOR
CHARISREL:
	;CHECK FOR LESS THAN "<"
	CMP		#0x3C
	BMI		CHARISRELA	
	;CHECK FOR GREATER THAN ">"
	CMP		#0x3F
	BMI		CHARISRELB	
CHARISRELA:
	CLC
	RTS
CHARISRELB:
	SEC
	RTS


;RETURNS TRUE IF VALUE IS AN UPPERCASE LETTER
;ON ENTRY:
;	A = VALUE
;ON RETURN:
;	A = VALUE ON ENTRY
;	CF = 0 IF VALUE IS NOT AN UPPERCASE LETTER
;	CF = 1 IF VALUE IS AN UPPERCASE LETTER
CHARISUPPER:
	;CHECK FOR LESS THAN "A"
	CMP		#0x41
	BMI		CHARISUPPERA
	;CHECK FOR GREATER THAN "Z"
	CMP		#0x5B
	BMI		CHARISUPPERB
CHARISUPPERA:
	CLC
	RTS
CHARISUPPERB:
	SEC
	RTS
	
	
;CONVERTS THE CHARACTER IN A TO AN INTEGER
;ON ENTRY:
;	A = CHARACTER
;ON RETURN:
;	C = 0 IF CHARACTER IS AN INTEGER
;			A = INTEGER VALUE
;	C = 1 IF CHARACTER IS NOT AN INTEGER
;			A = 0x00
CHARTOINT:
	;CHECK FOR LESS THAN "0"
	SEC
	SBC		#0x30
	BMI		CHARTOINTA	
	;CHECK FOR GREATER THAN "9"
	CMP		#0x0A
	BPL		CHARTOINTA	
	CLC
	RTS
CHARTOINTA:
	LDA		#0x00
	SEC
	RTS
	

;CONVERTS AN UPPERCASE LETTER TO A LOWERCASE LETTER
;ON ENTRY:
;	A = CHARACTER
;ON RETURN:
;	C = 0 IF CHARACTER WAS UPPERCASE
;		A = CONVERTED VALUE
;	C = 1 IF CHARACTER WAS NOT UPPERCASE
;		A = VALUE ON ENTRY
CHARTOLOWER:
	;CHECK FOR LESS THAN "A"
	CMP		#0x41
	BMI		CHARTOLOWERA
	;CHECK FOR GREATER THAN "Z"
	CMP		#0x5B
	BPL		CHARTOLOWERA
	;CONVERT TO LOWERCASE
	ADC		#0x20
	RTS
CHARTOLOWERA:
	SEC
	RTS


;CONVERTS A LOWERCASE LETTER TO AN UPPERCASE LETTER
;ON ENTRY:
;	A = CHARACTER
;ON RETURN:
;	C = 0 IF CHARACTER WAS LOWERCASE
;		A = CONVERTED VALUE
;	C = 1 IF CHARACTER WAS NOT LOWERCASE
;		A = VALUE ON ENTRY
CHARTOUPPER:
	;CHECK FOR LESS THAN "a"
	CMP		#0x61
	BMI		CHARTOUPPERA
	;CHECK FOR GREATER THAN "z"
	CMP		#0x7B
	BPL		CHARTOUPPERA
	;CONVERT TO UPPERCASE
	SEC
	SBC		#0x20
	CLC
	RTS
CHARTOUPPERA:
	SEC
	RTS
